import { useEffect, useMemo, useState } from "react";
import spellsJson from "../data/spells.json";
import modifiersJson from "../data/modifiers.json";
import equipmentJson from "../data/equipment.json";
import archetypesJson from "../data/archetypes.json";
import conceptsJson from "../data/build-concepts.json";
import sourcesJson from "../data/sources.json";
import type { ArchetypeRecord, BuildConcept, BuildState, CharacterClass, DataStatus, EquipmentSet, EquipmentSlot, Modifier, Race, Spell, View } from "./types";
import SkillTree from "./SkillTree";
import "./v2.css";

const SPELLS=spellsJson as Spell[];
const MODIFIERS=modifiersJson as Modifier[];
const SETS=equipmentJson.sets as EquipmentSet[];
const SLOTS=equipmentJson.slots as EquipmentSlot[];
const ARCHETYPES=archetypesJson as ArchetypeRecord[];
const CONCEPTS=conceptsJson as BuildConcept[];
const SOURCES=sourcesJson as Array<{id:string;label:string;url:string;status:DataStatus;scope:string}>;
const RACES:Race[]=["Human","Elf","Minotaur"];
const CLASSES:CharacterClass[]=["Mage","Brawler","Shadow"];
const STORAGE_KEY="buildraeth-draft-v3";
const emptyEquipment=()=>Object.fromEntries(SLOTS.map((s)=>[s.id,""])) as Record<string,string>;
const DEFAULT_BUILD:BuildState={schemaVersion:3,title:"Untitled Build",race:"Human",characterClass:"Mage",level:25,skillPointBudget:60,treeAllocations:{},spells:Array.from({length:5},()=>({spellId:"",modifierId:""})),equipment:emptyEquipment(),notes:""};

function encode(value:unknown){const bytes=new TextEncoder().encode(JSON.stringify(value));let binary="";for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
function decode(value:string):BuildState|null{try{const p=value.replaceAll("-","+").replaceAll("_","/")+"=".repeat((4-value.length%4)%4);const bytes=Uint8Array.from(atob(p),(c)=>c.charCodeAt(0));const raw=JSON.parse(new TextDecoder().decode(bytes)) as Partial<BuildState>;if(!raw||!RACES.includes(raw.race as Race)||!CLASSES.includes(raw.characterClass as CharacterClass))return null;const slots=Array.isArray(raw.spells)?raw.spells.slice(0,5):[];while(slots.length<5)slots.push({spellId:"",modifierId:""});return {...DEFAULT_BUILD,...raw,schemaVersion:3,skillPointBudget:raw.skillPointBudget??60,treeAllocations:raw.treeAllocations??{},spells:slots.map((s)=>({spellId:s?.spellId??"",modifierId:s?.modifierId??""})),equipment:{...emptyEquipment(),...(raw.equipment??{})}} as BuildState}catch{return null}}
function initialBuild(){const h=new URLSearchParams(location.hash.replace(/^#/,"")).get("build");if(h){const d=decode(h);if(d)return d}const saved=localStorage.getItem(STORAGE_KEY);if(saved){try{const raw=JSON.parse(saved);return {...DEFAULT_BUILD,...raw,schemaVersion:3,skillPointBudget:raw.skillPointBudget??60,treeAllocations:raw.treeAllocations??{},equipment:{...emptyEquipment(),...raw.equipment}}}catch{}}return DEFAULT_BUILD}
function RuneMark({small=false}:{small?:boolean}){return <span className={small?"rune-mark rune-mark--small":"rune-mark"} aria-hidden="true"><span/></span>}
function StatusBadge({status}:{status:DataStatus}){const labels:Record<DataStatus,string>={"ea-official":"EA Official","developer-confirmed":"Dev Confirmed","demo-legacy":"Demo Legacy","community-pending":"Pending"};return <span className={"status-badge status-"+status}>{labels[status]}</span>}

export default function App(){
  const [view,setView]=useState<View>("builder");
  const [build,setBuild]=useState<BuildState>(initialBuild);
  const [shareLabel,setShareLabel]=useState("Copy build link");
  const [spellQuery,setSpellQuery]=useState(""),[spellElement,setSpellElement]=useState("All"),[setQuery,setSetQuery]=useState("");
  const [compendiumMode,setCompendiumMode]=useState<"spells"|"sets">("spells");
  useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(build)),[build]);
  const spellMap=useMemo(()=>new Map(SPELLS.map((s)=>[s.id,s])),[]);
  const setMap=useMemo(()=>new Map(SETS.map((s)=>[s.id,s])),[]);
  const archetype=useMemo(()=>ARCHETYPES.find((a)=>a.race===build.race&&a.characterClass===build.characterClass),[build.race,build.characterClass]);
  const setCounts=useMemo(()=>{const m=new Map<string,number>();Object.values(build.equipment).filter(Boolean).forEach((id)=>m.set(id,(m.get(id)??0)+1));return m},[build.equipment]);
  const updateSpell=(i:number,id:string)=>setBuild((b)=>{const s=[...b.spells];s[i]={spellId:id,modifierId:""};return {...b,spells:s}});
  const updateMod=(i:number,id:string)=>setBuild((b)=>{const s=[...b.spells];s[i]={...s[i],modifierId:id};return {...b,spells:s}});
  const share=async()=>{const u=new URL(location.href);u.hash="build="+encode(build);history.replaceState(null,"",u);try{await navigator.clipboard.writeText(u.toString());setShareLabel("Copied!")}catch{setShareLabel("Link ready in address bar")}setTimeout(()=>setShareLabel("Copy build link"),1800)};
  const exportJson=()=>{const blob=new Blob([JSON.stringify(build,null,2)],{type:"application/json"}),href=URL.createObjectURL(blob),a=document.createElement("a");a.href=href;a.download=(build.title||"buildraeth-build").toLowerCase().replace(/[^a-z0-9]+/g,"-")+".json";a.click();URL.revokeObjectURL(href)};
  const importJson=async(file?:File)=>{if(!file)return;try{const parsed=JSON.parse(await file.text());const d=decode(encode(parsed));if(d)setBuild(d)}catch{}};
  const loadConcept=(c:BuildConcept)=>{const equipment=emptyEquipment();c.setIds.forEach((id,i)=>{if(SLOTS[i])equipment[SLOTS[i].id]=id});setBuild({...DEFAULT_BUILD,title:c.title,race:c.race,characterClass:c.characterClass,spells:c.spellIds.slice(0,5).map((spellId)=>({spellId,modifierId:""})),equipment,notes:c.note});setView("builder");scrollTo({top:0,behavior:"smooth"})};
  const filteredSpells=SPELLS.filter((s)=>{const q=spellQuery.trim().toLowerCase();return(spellElement==="All"||s.element===spellElement)&&(!q||[s.name,s.element,s.damageType??"",s.source,s.statusEffect??"",...s.roles].join(" ").toLowerCase().includes(q))});
  const filteredSets=SETS.filter((s)=>!setQuery.trim()||(s.name+" "+s.effect).toLowerCase().includes(setQuery.toLowerCase()));
  const nav=(v:View,label:string)=><button className={view===v?"active":""} onClick={()=>setView(v)}>{label}</button>;

  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>setView("builder")}><RuneMark small/><span className="brand-copy"><strong>BUILDRAETH</strong><small>UNOFFICIAL DIMRAETH BUILDER</small></span></button><nav className="main-nav">{nav("builder","Builder")}{nav("browse","Builds")}{nav("compendium","Compendium")}{nav("sources","Sources")}</nav><a className="ghost-button github-link" href="https://github.com/afterhours247/Buildraeth" target="_blank" rel="noreferrer">GitHub ↗</a></header>
    <main>
      {view==="builder"&&<>
        <section className="hero hero-compact"><div className="hero-copy"><span className="eyebrow">THE THEORYCRAFTING FORGE</span><h1>Make the build.<br/>Keep the receipts.</h1><p>Five spells, archived modifiers, equipment-set planning, source labels, local saves, and shareable links. Current EA facts stay separate from historical Demo data.</p><div className="hero-badges"><StatusBadge status="ea-official"/><span>46 archived spells</span><span>23 archived sets</span><span>$0 backend</span></div></div><div className="hero-rune"><RuneMark/><div className="orbit orbit-a"/><div className="orbit orbit-b"/></div></section>
        <section className="builder-toolbar"><div><span className="kicker">DRAFT</span><strong>Saved automatically in this browser · skill-tree allocations are included in share links</strong></div><div className="toolbar-actions"><label className="ghost-button file-button">Import JSON<input type="file" accept="application/json" onChange={(e)=>importJson(e.target.files?.[0])}/></label><button className="ghost-button" onClick={exportJson}>Export JSON</button><button className="primary-button inline-primary" onClick={share}>⛓ {shareLabel}</button></div></section>
        <SkillTree build={build} setBuild={setBuild} spells={SPELLS} modifiers={MODIFIERS}/>
        <section className="forge-layout">
          <aside className="panel parchment-panel identity-panel"><div className="panel-heading"><span className="step-number">I</span><div><span className="kicker">ARCHETYPE</span><h2>Choose the foundation</h2></div></div>
            <label className="field"><span>Build name</span><input value={build.title} maxLength={64} onChange={(e)=>setBuild({...build,title:e.target.value})}/></label>
            <label className="field"><span>Level target</span><input type="number" min={1} max={25} value={build.level} onChange={(e)=>setBuild({...build,level:Math.max(1,Math.min(25,Number(e.target.value)||1))})}/><small>EA Act I cap is currently 25.</small></label>
            <div className="field"><span>Race</span><div className="choice-grid">{RACES.map((r)=><button key={r} className={build.race===r?"choice active":"choice"} onClick={()=>setBuild({...build,race:r,treeAllocations:{}})}><span className="choice-sigil">{r[0]}</span>{r}</button>)}</div></div>
            <div className="field"><span>Class</span><div className="choice-grid">{CLASSES.map((c)=><button key={c} className={build.characterClass===c?"choice active":"choice"} onClick={()=>setBuild({...build,characterClass:c,treeAllocations:{}})}><span className="choice-sigil">{c[0]}</span>{c}</button>)}</div></div>
            <div className="archetype-callout"><span className="kicker">ARCHETYPE RECORD</span><strong>{archetype?.name||build.race+" "+build.characterClass}</strong><p>{archetype?.note||"The pairing is current EA, but a reliable archetype name has not been published in this source set."}</p>{archetype&&<StatusBadge status={archetype.dataStatus}/>}</div>
          </aside>
          <section className="panel loadout-panel"><div className="panel-heading inverse"><span className="step-number">II</span><div><span className="kicker">SPELL LOADOUT</span><h2>Five slots, each with its own history</h2></div><span className="source-chip">46 ARCHIVED</span></div><div className="loadout-list">{build.spells.map((slot,i)=>{const selected=spellMap.get(slot.spellId),mods=MODIFIERS.filter((m)=>m.spellId===slot.spellId);return <article className="loadout-row" key={i}><span className="slot-gem">{i+1}</span><div className="loadout-controls"><label><span>Spell</span><select value={slot.spellId} onChange={(e)=>updateSpell(i,e.target.value)}><option value="">Unassigned</option>{SPELLS.map((s)=><option value={s.id} key={s.id}>{s.name} · {s.element}</option>)}</select></label><label><span>Modifier</span><select value={slot.modifierId} disabled={!mods.length} onChange={(e)=>updateMod(i,e.target.value)}><option value="">{mods.length?"No modifier selected":"No archived modifiers"}</option>{mods.map((m)=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label></div><div className="spell-meta">{selected?<><strong>{selected.element}{selected.damageType?" · "+selected.damageType:""}</strong><span>{selected.roles.join(" / ")}{selected.statusEffect?" · "+selected.statusEffect:""}</span><StatusBadge status={selected.dataStatus}/></>:<span className="empty-copy">Pick a spell from the archive.</span>}</div></article>})}</div><div className="data-warning"><strong>⚑ Version boundary:</strong> the spell/modifier archive is Demo/playtest data unless explicitly labelled otherwise. It is useful for planning, not a claim that every number survived Early Access unchanged.</div></section>
          <aside className="panel summary-panel"><div className="panel-heading inverse"><span className="step-number">III</span><div><span className="kicker">BUILD SCROLL</span><h2>{build.title||"Untitled Build"}</h2></div></div><div className="build-card"><div className="build-card-title"><RuneMark small/><div><strong>{archetype?.name||build.race+" "+build.characterClass}</strong><span>Level {build.level} · {build.race} · {build.characterClass}</span></div></div><div className="slot-stack">{build.spells.map((s,i)=>{const spell=spellMap.get(s.spellId),mod=MODIFIERS.find((m)=>m.id===s.modifierId);return <div className="slot-row" key={i}><span>{i+1}</span><div><strong>{spell?.name||"Open slot"}</strong>{mod&&<small>{mod.name}</small>}</div></div>})}</div><div className="mini-set-summary"><span>Set plan</span>{setCounts.size?[...setCounts.entries()].map(([id,count])=><small key={id}>{setMap.get(id)?.name||id} ×{count}</small>):<small>No set pieces assigned yet</small>}</div><label className="notes"><span>Build notes</span><textarea value={build.notes} placeholder="Rotation, breakpoints, synergies, things to verify in-game..." onChange={(e)=>setBuild({...build,notes:e.target.value})}/></label></div></aside>
        </section>
        <section className="equipment-section"><div className="section-heading-row"><div><span className="eyebrow">EQUIPMENT PLAN</span><h2>Eight archived gear slots</h2></div><p>Choose a set identity per slot. Random stats and live EA item rolls are intentionally not invented.</p></div><div className="equipment-grid">{SLOTS.map((slot)=><label className="equipment-slot" key={slot.id}><span className="equipment-rune">{slot.name[0]}</span><div><strong>{slot.name}</strong><select value={build.equipment[slot.id]||""} onChange={(e)=>setBuild({...build,equipment:{...build.equipment,[slot.id]:e.target.value}})}><option value="">Unassigned</option>{SETS.map((set)=><option value={set.id} key={set.id}>{set.name}</option>)}</select></div></label>)}</div></section>
      </>}
      {view==="browse"&&<section className="page-section"><div className="section-intro"><span className="eyebrow">BUILD CONCEPTS</span><h1>Directions, not commandments.</h1><p>Source-backed mechanic concepts and historical synergies, not rankings. Open one, change it, and share your version.</p></div><div className="template-grid concept-grid">{CONCEPTS.map((c)=><article className="template-card concept-card" key={c.id}><div className="template-topline"><span>{c.race}</span><span>{c.characterClass}</span></div><h2>{c.title}</h2><small className="concept-subtitle">{c.subtitle}</small><p>{c.note}</p><div className="tag-row">{c.tags.map((t)=><span key={t}>{t}</span>)}</div><div className="concept-spells">{c.spellIds.map((id)=><small key={id}>{spellMap.get(id)?.name||id}</small>)}</div><button className="primary-button compact" onClick={()=>loadConcept(c)}>Open in builder</button></article>)}</div><div className="community-callout"><RuneMark small/><div><strong>Community publishing, without a backend bill</strong><p>Share links work now. Curated public builds can come through GitHub issues/PRs until a real database is worth adding.</p></div><a className="ghost-button" target="_blank" rel="noreferrer" href="https://github.com/afterhours247/Buildraeth/issues/new?template=build-submission.yml">Submit build ↗</a></div></section>}
      {view==="compendium"&&<section className="page-section"><div className="section-intro"><span className="eyebrow">COMPENDIUM</span><h1>The useful archive.</h1><p>Search the data without hiding its age. Demo records remain visibly Demo records until the EA client confirms them.</p></div><div className="compendium-tabs"><button className={compendiumMode==="spells"?"active":""} onClick={()=>setCompendiumMode("spells")}>Spells · 46</button><button className={compendiumMode==="sets"?"active":""} onClick={()=>setCompendiumMode("sets")}>Sets · 23</button></div>{compendiumMode==="spells"?<><div className="filter-bar"><input placeholder="Search spell, status, source..." value={spellQuery} onChange={(e)=>setSpellQuery(e.target.value)}/><select value={spellElement} onChange={(e)=>setSpellElement(e.target.value)}><option>All</option>{[...new Set(SPELLS.map((s)=>s.element))].sort().map((el)=><option key={el}>{el}</option>)}</select><span>{filteredSpells.length} results</span></div><div className="record-grid">{filteredSpells.map((s)=><article className="record-card" key={s.id}><div className={"element-glyph element-"+s.element.toLowerCase()}>{s.element[0]}</div><div><div className="record-title-row"><h2>{s.name}</h2><StatusBadge status={s.dataStatus}/></div><p>{s.element}{s.damageType?" · "+s.damageType:""} · {s.roles.join(" / ")}</p>{s.statusEffect&&<span className="effect-chip">{s.statusEffect}</span>}<small>{MODIFIERS.filter((m)=>m.spellId===s.id).length} archived modifiers</small></div></article>)}</div></>:<><div className="filter-bar"><input placeholder="Search set or effect..." value={setQuery} onChange={(e)=>setSetQuery(e.target.value)}/><span>{filteredSets.length} results</span></div><div className="record-grid">{filteredSets.map((s)=><article className="record-card" key={s.id}><div className="set-glyph">{s.name[0]}</div><div><div className="record-title-row"><h2>{s.name}</h2><StatusBadge status={s.dataStatus}/></div><p>{s.effect}</p></div></article>)}</div></>}</section>}
      {view==="sources"&&<section className="page-section"><div className="section-intro"><span className="eyebrow">PROVENANCE</span><h1>No mystery meat data.</h1><p>Buildraeth records whether a fact describes current Early Access, a developer design statement, or the older Demo.</p></div><div className="source-grid">{SOURCES.map((s)=><a className="source-card" href={s.url} target="_blank" rel="noreferrer" key={s.id}><div><StatusBadge status={s.status}/><h2>{s.label}</h2><p>{s.scope}</p></div><span>Open source ↗</span></a>)}</div><div className="source-note large-source-note"><RuneMark small/><div><strong>Data update policy</strong><p>Official current EA sources win. Developer posts remain design evidence. Historical wiki records never silently graduate to current EA status. Community corrections should include a screenshot, patch/version, and where the value was observed.</p></div></div></section>}
    </main>
    <footer><span>Buildraeth · unofficial fan project · data snapshot 2026-09-19</span><span>Not affiliated with or endorsed by Mudtek.</span></footer>
  </div>;
}
